# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_location_who_are_locals'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_locations',
            field=models.ManyToManyField(to='locations.Location'),
        ),
    ]
