# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20161220_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='amount_refunded',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='application',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
