# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20161220_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount_refunded',
            field=models.IntegerField(),
        ),
    ]
