# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20161220_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created',
            field=models.IntegerField(default=111111),
            preserve_default=False,
        ),
    ]
