# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('locations', '0004_auto_20161219_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='who_are_locals',
            field=models.ManyToManyField(to='profiles.profile'),
        ),
    ]
